// <auto-generated />
using System;
using APBD_kolos2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_kolos2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_kolos2.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            ClientId = 2,
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dawid",
                            LastName = "Zygzak"
                        });
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Mechanic", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("MechanicId");

                    b.ToTable("Mechanic");

                    b.HasData(
                        new
                        {
                            MechanicId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            LicenseNumber = "123456789"
                        },
                        new
                        {
                            MechanicId = 2,
                            FirstName = "Dawid",
                            LastName = "Zygzak",
                            LicenseNumber = "987654321"
                        });
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            BaseFee = 200m,
                            Name = "Zmiana oleju"
                        },
                        new
                        {
                            ServiceId = 2,
                            BaseFee = 100m,
                            Name = "Przeglad"
                        });
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Visit");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            ClientId = 1,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MechanicId = 1
                        },
                        new
                        {
                            VisitId = 2,
                            ClientId = 2,
                            Date = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MechanicId = 2
                        });
                });

            modelBuilder.Entity("APBD_kolos2.Entities.VisitService", b =>
                {
                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("VisitId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Visit_Service");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            ServiceId = 1,
                            ServiceFee = 200m
                        },
                        new
                        {
                            VisitId = 1,
                            ServiceId = 2,
                            ServiceFee = 100m
                        },
                        new
                        {
                            VisitId = 2,
                            ServiceId = 1,
                            ServiceFee = 200m
                        });
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Visit", b =>
                {
                    b.HasOne("APBD_kolos2.Entities.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_kolos2.Entities.Mechanic", "Mechanic")
                        .WithMany("Visits")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("APBD_kolos2.Entities.VisitService", b =>
                {
                    b.HasOne("APBD_kolos2.Entities.Service", "Service")
                        .WithMany("VisitServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_kolos2.Entities.Visit", "Visit")
                        .WithMany("VisitServices")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Client", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Mechanic", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Service", b =>
                {
                    b.Navigation("VisitServices");
                });

            modelBuilder.Entity("APBD_kolos2.Entities.Visit", b =>
                {
                    b.Navigation("VisitServices");
                });
#pragma warning restore 612, 618
        }
    }
}
